/*
 * Copyright 2017-2022 asanetargoss
 *
 * This file is part of Hardcore Alchemy Core.
 *
 * Hardcore Alchemy Core is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License version 3 or, at
 * your option, any later version of the GNU Lesser General Public License as
 * published by the Free Software Foundation.
 *
 * Hardcore Alchemy Core is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with Hardcore Alchemy Core. If not, see <http://www.gnu.org/licenses/>.
 */

package targoss.hardcorealchemy.coremod;

import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Retention;

/**
 * An informational annotation for methods called
 * from code generated by coremod patches.
 * 
 * DEPRECATED: Please use static inner classes in the coremods
 * instead. For example:
 * 
 * String hookClass = getClass().getName() + "$Hooks";
 * String hookMethodOwner = hookClass.replace('.', '/');
 * 
 * Where "Hooks" is the name of the static inner class containing
 * callbacks used by the coremod.
 */
@Deprecated
@Retention(RUNTIME)
public @interface CoremodHook {

}
