package targoss.hardcorealchemy.coremod;

import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Retention;
/**
 * An informational annotation for methods called
 * from code generated by coremod patches.
 */
@Retention(RUNTIME)
public @interface CoremodHook {

}
